#!/bin/bash
BASEDIR="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
export TOOL_NAME="hercule"
IMAGE_NAME="$TOOL_NAME"
CONTAINER_NAME="$TOOL_NAME""_container"

if [[ "$(docker images -q $IMAGE_NAME 2> /dev/null)" == ""  ]]; then
  echo "Docker Image $(TOOL_NAME) not found"
  exit 1
fi


if [ ! "$(docker ps -q -f name=$CONTAINER_NAME)"  ]; then
    if [ ! "$(docker ps -aq -f status=exited -f name=$CONTAINER_NAME)"  ]; then
        docker rm $TOOL_NAME
    fi
    docker run -d -ti --name $CONTAINER_NAME -v $BASEDIR:/$TOOL_NAME --cap-add=SYS_PTRACE --security-opt seccomp=unconfined $IMAGE_NAME
fi

docker exec -it $CONTAINER_NAME bash
