KEY_BUG_ID = "bug_id"
KEY_BENCHMARK = "benchmark"
KEY_ID = "id"
KEY_SUBJECT = "subject"
KEY_LANGUAGE = "language"
KEY_ENABLED = "enabled"

ARG_CPU_COUNT = "--cpu-count"
ARG_USE_GPU = "--use-gpu"
ARG_UI = "--ui"
ARG_CACHE = "--cache"
ARG_DATA_PATH = "--dir-data"
ARG_DEBUG_MODE = "--debug"
ARG_PURGE = "--purge"
ARG_RERUN = "--rerun"
ARG_PACKAGE_FILE = "--file"
ARG_LASTPYMILE = "--lastpymile"
ARG_NO_DEPS= "--no-dependencies"

UI_STARTED_AT = "Started at"
UI_SHOULD_FINISH = "Should finish by"
UI_STATUS = "Status"
UI_DURATION = "Duration"
